config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'application#index'
  devise_for :users#, :skip => :registrations
  
  resources :restaurants do
    resources :menu_items
    resources :branches do
      resources :orders do
        resources :order_lines
      end
    end
  end
  get 'restaurant/:city', to: 'restaurants#by_city', as: "by_city"
  get 'orders/', to: 'orders#orders', as: "orders"

  # devise_for :admins, class_name: 'Admin', skip: [:sessions, :registrations]
  # devise_for :vendors, class_name: 'Vendor', skip: :sessions
  # devise_for :customers, class_name: 'Customer', skip: :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/branch.rb
class Branch < ApplicationRecord
  belongs_to :restaurant
  has_many :orders
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
    before_action :set_branch, only: [:show, :edit, :update, :destroy]
    
      def index
        @restaurants = Restaurant.find(params[:restaurant_id])
        @branches = @restaurants.branches
 
        
      end
    
      def show
        if (!current_user)
          redirect_to(root_path, alert: "Login to Order or view")
        else
          @menu_items = @restaurant.menu_items
          @order = Order.where("branch_id = ? and user_id = ?", @branch.id, current_user.id).last
          if !@order
            @order= Order.create(branch_id: @branch.id, user_id: current_user.id, total_price: 0)
          end
        end

      end

      def new
          @branch = Branch.new
      end
      
    
      def create
        if can? :create, Branch
            puts branch_params
            @branch = Branch.new(branch_params)
            @branch.restaurant_id = params[:restaurant_id]
            if @branch.save

                redirect_to restaurant_branch_path, notice: "Branch successfully created"

            else
                
                redirect_to new_restaurant_branch_path, alert: "Something went wrong"
            end
        else
          redirect_to edit_restaurant_branch_path, alert: "Something went wrong"
        end
      end
    
      def update
        if @branch.update(branch_params)
            
            redirect_to restaurant_branch_path, notice: "Branch was successfully updated"
          else
            
            redirect_to edit_restaurant_branch_path, alert: "Something went wrong"
          end
      end
    
      def edit
        if !can? :edit, @branch
            
            redirect_to restaurant_branch_path, alert: "Something went wrong"
        end
      end
    
      def destroy
        if current_user.admin?
            if @branch.destroy
                
                redirect_to restaurant_branch_path, notice: 'Branch was successfully deleted.'
            else
                
                redirect_to restaurant_branch_path, alert: "Something went wrong"
            end
        else
            flash[:error] = "No permission!"
        end
      end

      private
      # Use callbacks to share common setup or constraints between actions.
          def set_branch
            puts params[:restaurant_id]
            @restaurant = Restaurant.find(params[:restaurant_id])
            @branch = @restaurant.branches.find(params[:id])
            
          end
  
          def branch_params
              params.require(:branch).permit(:city, :address)
          end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_edit_form.html.erb
<div class="w-1/4 my-8 m-auto shadow-lg m-4 p-4 bg-white flex justify-center card mt-8">
  <%= simple_form_for  @branch, url: restaurant_branch_path(@restaurant, @branch), method: :put do |f| %>
    <div class="text-gray-700">
      <%= f.input :city, input_html:{class:  "mb-4 border form-input mt-1 block w-64  text-gray-600"}%>
    </div>

    <div class="text-gray-700">
      <%= f.input :address , input_html:{class:  "mb-4 border form-input mt-1 block w-64  text-gray-600"}%>
    </div>
    <div class="btn rounded">
      <%= f.submit 'submit', class: "  bg-sp-mn hover:bg-sp-sc text-white  font-bold py-2 px-4 rounded m-auto w-full" %>
    </div>
  <% end %>
</div>

app/views/branches/_form.html.erb
<div class="w-1/4 my-8 m-auto shadow-lg m-4 p-4 bg-white flex justify-center card mt-8">
<%= simple_form_for  @branch, url: restaurant_branches_path, method: :post do |f| %>
  <div class="text-gray-700">
    <%= f.input :city, input_html:{class:  "mb-4 border form-input mt-1 block w-64  text-gray-600"} %>
  </div>
  <div class="text-gray-700">
    <%= f.input :address, input_html:{class:  "mb-4 border form-input mt-1 block w-64  text-gray-600"} %>
  </div>
  <%= f.submit 'submit', class: "  bg-sp-mn hover:bg-sp-sc text-white  font-bold py-2 px-4 rounded m-auto w-full"  %>
<% end %>
</div>

app/views/branches/edit.html.erb
  <div class="font-thin text-center my-8 text-xl flex-1">
  <p>
    Edit Branch
  </p>
</div>
<%= render 'edit_form' %>

app/views/branches/index.html.erb
  <div class="font-thin text-center my-8 text-xl flex-1">
  <p>
    Choose Branch
  </p>
</div>
<div class="w-1/4 flex flex-col flex-wrap  m-auto mb-8">
  <% @branches.each do |b| %>
    <div class="rounded-lg overflow-hidden shadow-lg w-full h-24 text-left bg-white hover:bg-gray-200 mt-5 flex items-center m-auto">
      <img class="w-16 h-16 rounded-full mr-4 bg-sp-mn ml-2"/>
      <p class="text-lg text-gray-800">
      <%= link_to "#{b.city}, #{b.address}", restaurant_branch_path(params[:restaurant_id], b)%>
      </p>
    </div>
  <% end %>
</div>

<% if can? :create, Branch %>
<div class="flex justify-center mt-24">
<div class="flex flex-col justify-center h-24  my-3  mx-24  w-1/4 rounded-lg overflow-hidden shadow-lg m-4 bg-white card m-auto">
  <div class="font-bold text-lg mb-1 flex-1 text-center text-red-800">
    <p class="mt-4">
      Admin Control
    </p>
  </div>
    <%= link_to 'New Branch', new_restaurant_branch_path, class: "bg-gray-500 hover:bg-red-800 text-white font-bold py-2 px-4 rounded m-auto mt-2 mb-8" %>
  </div>
</div>
<% end %>

app/views/branches/new.html.erb
  <div class="font-thin text-center my-8 text-xl flex-1">
  <p>
    Create New Branch
  </p>
</div>
<%= render 'form' %>

app/views/branches/show.html.erb
  <%#= link_to "Start A New Order", new_restaurant_branch_order_path(@restaurant, @branch), id: "link-to-new-order", class: "invisible bg-gray-500 hover:bg-red-500 text-white font-bold py-2 px-4 rounded m-auto" %>
  <div class="font-thin text-center my-8 text-xl flex-1">
  <p>
    Menu Order
  </p>
</div>
<div class="flex flex-col">
  <div class="container flex flex-wrap justify-center m-auto mb-8" id="cards">
    <% @menu_items.each do |m| %>
      <div class="lg:w-1/6 sm:w-1/2 xl:1/6 rounded-lg overflow-hidden shadow-lg m-3 bg-white card" id="<%= "#{m.id}-#{@order.id}" %>">
        <%= image_tag "burger.jpg" %>
        <div class="px-6 py-4 flex flex-col items-stretch flex-wrap jusrify-end">
          <div class="font-bold text-lg mb-1 flex-1">
            <p>
              <%= m.name %>
            </p>
            <p class="text-right">
              <%= m.ar_name %>
            </p>
          </div>
          <p class="text-gray-700 text-sm flex-1">
            <%= m.description %>
          </p>
          <p class="text-gray-600 text-base flex-1 text-center my-2">
            <%= m.price %> SAR
          </p>
          <div class=" m-auto flex justify-around self-stretch w-full mt-2">
            <button class="text-white quantity_down bg-red-500 w-8 h-8 rounded-full hover:bg-red-300" type=button>
              -
            </button>
            <p class="text-gray-700 cart_quantity">
              <%= @order.order_lines.where("menu_item_id = ?", m.id).sum(:quantity) %>
            </p>
            <button class="text-white quantity_up bg-green-500 w-8 h-8 rounded-full hover:bg-green-300 self-center" type=button>
              +
            </button>
          </div>
        </div>
        <div class="w-full px-6 py-4" id="add-order">
          
          <%= link_to "Add", new_restaurant_branch_order_order_line_path(@restaurant.id, @branch.id, @order.id, params[:quantity]) , remote: true, class: "link-to-new-order w-full" %>
          
        </div>
        <div id="orders"></div>
      </div>
    <% end %>


  </div>
  <%if !@order.order_lines.empty?%>
  <div class="flex  mb-3 justify-around mx-24 mt-16" id="cards">
      <div class="w-3/4 rounded-lg overflow-hidden shadow-lg m-4 bg-white card ">
          <div class="font-bold text-lg mb-1 flex-1 text-center">
            <p class="mt-4">
              Order
            </p>
          </div>
          <table class="table-fixed w-3/5 text-left m-auto ">
            <thead>
            <tr>
              <th class="w-1/2 px-4 py-2 text-gray-800">Items</th>
              <th class="w-1/5 px-4 py-2 text-gray-800">Quantity</th>
              <th class="w-1/6 px-4 py-2 text-gray-800">Price</th>
              <th class="w-1/6 px-4 py-2 text-gray-800"></th>
              </tr>
            </thead>
            <tbody>
            <%@order.order_lines.each do |o|%>
            <tr>
            
              <td class=" px-4 py-2"> <%= o.menu_item.name %> </td>
              <td class=" px-4 py-2"> <%= o.quantity %> </td>
              <td class=" px-4 py-2"> <%= o.price %> </td>
              <td class=" px-4 py-2"> <%= link_to "X", restaurant_branch_order_order_line_path(@restaurant, @branch, o.order, o), method: :delete, class: "text-white quantity_up bg-red-600 w-4 h-4 rounded-full hover:bg-red-800 self-center"%>
            </tr>
            <%end%>
            </tbody>
          </table>
          <p class="text-center m-auto mt-8 mb-4">
            <span class="text-gray-800"> Total Price: <%= @order.total_price%><span>
            
          </p>
 
      </div>
  </div>

  <%end%>
  
  <%if !@order.order_lines.empty?%>
    <%= link_to "Start A New Order", new_restaurant_branch_order_path(@restaurant, @branch), id: "place-oerder", class: "bg-gray-500 hover:bg-red-500 text-white font-bold py-2 px-4 rounded m-auto" %>
    <%= link_to "Checkout", restaurant_branch_order_path(@restaurant, @branch, @order), id: "checked-out", class: "bg-gray-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded m-auto mt-2 mb-8" %>
  <%end%>
</div>
<% if can? :update, @branch %>
<div class="flex justify-center mt-24">
<div class="flex flex-col justify-center h-24  my-3  mx-24  w-1/4 rounded-lg overflow-hidden shadow-lg m-4 bg-white card m-auto">
  <div class="font-bold text-lg mb-1 flex-1 text-center text-red-800">
    <p class="mt-4">
      Admin Control
    </p>
  </div>
    <%= link_to 'Edit Branch', edit_restaurant_branch_path, class: "bg-gray-500 hover:bg-red-800 text-white font-bold py-2 px-4 rounded m-auto mt-2 mb-8" %>
  </div>
</div>
<% end %>