config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'application#index'
  devise_for :users#, :skip => :registrations
  
  resources :restaurants do
    resources :menu_items
    resources :branches do
      resources :orders do
        resources :order_lines
      end
    end
  end
  get 'restaurant/:city', to: 'restaurants#by_city', as: "by_city"
  get 'orders/', to: 'orders#orders', as: "orders"

  # devise_for :admins, class_name: 'Admin', skip: [:sessions, :registrations]
  # devise_for :vendors, class_name: 'Vendor', skip: :sessions
  # devise_for :customers, class_name: 'Customer', skip: :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    belongs_to :user
    has_many :menu_items
    has_many :branches
    accepts_nested_attributes_for :branches, reject_if: :all_blank, allow_destroy: true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    before_action :set_appointment, only: [:show, :edit, :update, :destroy]

    def by_city
        @restaurants_cities = Restaurant.joins(:branches).where(branches: {city: "#{params[:city]}"}).uniq
    end
    
    def index
        @restaurants = Restaurant.all
        @menu_items = MenuItem.all
        cities_arr = []
        @restaurants.each {|r| puts r.branches.each { |b| puts cities_arr << b.city}}
        @branches_by_cities = cities_arr.uniq!
    end

    def show
    end

    def new
        if can? :create, Restaurant
            @restaurant = Restaurant.new
        else
            flash[:error] = "No permission!"
        end
    end

    def create
        if can? :create, Restaurant
            @restaurant = Restaurant.new(restaurant_params)
            @restaurant.user_id = current_user.id
            
            if @restaurant.save
                
                redirect_to @restaurant, notice: "Restaurant successfully created"
            else
                
                redirect_to new_restaurant_path, alert: "Something went wrong"
            end
        else
            flash[:error] = "No permission!"
        end
    end

    def edit
        if !can? :update, @restaurant
            
            redirect_to @restaurant, alert: "Something went wrong"
        end
    end
    

    def update
        if @restaurant.update(restaurant_params)
        
          redirect_to @restaurant, notice: "Restaurant was successfully updated"
        else
        
          redirect_to edit_restaurant_path, alert: "Something went wrong"
        end
    end
    

    def destroy
        if current_user.admin?
            if @restaurant.destroy
                flash[:success] = 'Restaurant was successfully deleted.'
                redirect_to @restaurant, notice: 'Restaurant was successfully deleted.'
            else
                
                
            end
        else
            flash[:error] = "No permission!"
        end
    end
    private
    
        def set_appointment
        @restaurant = Restaurant.find(params[:id])
        end

        def restaurant_params
            params.require(:restaurant).permit(:name, :description, branches_attributes: [:id, :city, :address, :_destroy])
        end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
    def cities city
        @cities = Branch.joins(:restaurant).select(:city).where(restaurants: {name: city}).group(:city)
    end
end

app/views/restaurants/_branch_fields.html.erb
<div class="nested-fields">
<div class="text-gray-700">
  <%= f.input :city, input_html:{class:  "mb-4 border form-input mt-1 block w-64  text-gray-600"}  %>
  </div>
  <div class="text-gray-700">
  <%= f.input :address, input_html:{class:  "mb-4 border form-input mt-1 block w-64  text-gray-600"}  %>
 </div>
  <%= link_to_remove_association "remove branch", f , class: " mb-8 bg-sp-mn hover:bg-sp-sc text-white  font-bold py-2 px-4 rounded m-auto w-full"%>
</div>

app/views/restaurants/_form.html.erb
<div class="w-1/4 my-8 m-auto shadow-lg m-4 p-4 bg-white flex justify-center card mt-8">
<%= simple_form_for  @restaurant do |f| %>
  <div class="text-gray-700">
    <%= f.input :name, input_html:{class:  "mb-4 border form-input mt-1 block w-64  text-gray-600"} %>
  </div>
  <div class="text-gray-700">
    <%= f.input :description, input_html:{class:  "mb-4 border form-input mt-1 block w-64  text-gray-600"} %>
  </div>
  <div class="text-gray-700">
    <%= f.simple_fields_for :branches do |b|        %>
      <%= render 'branch_fields', f: b %>
    <% end %>
  </div>
  <div class="links">
    <%= link_to_add_association 'add branch', f, :branches, class:  "bg-sp-mn mt-8 hover:bg-sp-sc text-white  font-bold py-2 px-4 rounded m-auto w-full mb-2" %>
  </div>
  <%= f.submit 'Submit', class: "  bg-sp-mn hover:bg-sp-sc text-white  font-bold py-2 px-4 mt-4 rounded m-auto w-full" %>
<% end %>
</div>

app/views/restaurants/by_city.html.erb
<div class="font-thin text-center my-6 text-xl flex-1">
  <p>
    Choose Restaurant
  </p>
</div>

<div class="w-1/4 flex flex-col flex-wrap  m-auto my-8">
  <% @restaurants_cities.each do |r| %>
    <div class="rounded-lg overflow-hidden shadow-lg w-full h-24 text-left bg-white hover:bg-gray-200 mt-5 flex items-center m-auto">
      <img class="w-16 h-16 rounded-full mr-4 bg-sp-mn ml-2"/>
      <p class="text-lg text-gray-800">
      <%= link_to "#{r.name}", restaurant_branches_path(r)%>
      </p>
    </div>
  <% end %>
</div>

app/views/restaurants/edit.html.erb
  <div class="font-thin text-center my-8 text-xl flex-1">
  <p>
    Edit Restaurant
  </p>
</div>

<%=render 'form'%>

app/views/restaurants/index.html.erb
  <div class="font-thin text-center my-8 text-xl flex-1">
  <p>
    Choose Restaurant By City
  </p>
</div>
  
  <div class="container flex flex-wrap justify-center m-auto">
    <% @restaurants.each do |r| %>
      <div class="lg:w-1/5 sm:w-1/2 xl:1/4 rounded-lg overflow-hidden shadow-lg m-3 bg-white card">
          <%= image_tag "burger.jpg" %>
        <div class="px-6 py-4 flex flex-col items-stretch flex-wrap jusrify-end">
          <div class="font-bold text-lg mb-1 flex-1">
            <p>
              <%= r.name %>
            </p>
            <p class="text-gray-700 font-light text-sm">
              <%= r.description %>
            </p>
            <% cities(r.name).each do |c|%>
              <%if c%>
                <div class="inline-block bg-sp-mn hover:bg-gray-400 hover:text-gray-700 rounded-full px-3 py-1 mt-2 text-xs font-semibold text-white mr-2">
                    <%= (link_to "##{c.city}", by_city_path(city: c.city))  %>
                </div>
              <%end%>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <% if can? :create, Restaurant %>
<div class="flex justify-center mt-24">
<div class="flex flex-col justify-center h-24  my-3  mx-24  w-1/4 rounded-lg overflow-hidden shadow-lg m-4 bg-white card m-auto">
  <div class="font-bold text-lg mb-1 flex-1 text-center text-red-800">
    <p class="mt-4">
      Admin Control
    </p>
  </div>
    <%= link_to 'New Restaurant', new_restaurant_path, class: "mb-8 bg-gray-500 hover:bg-red-800 text-white font-bold py-2 px-4 rounded m-auto mt-2 mb-8" %>
  </div>
</div>
<% end %>

app/views/restaurants/new.html.erb
  <div class="font-thin text-center my-8 text-xl flex-1">
  <p>
    Create New Restaurant
  </p>
</div>

<%=render 'form'%>

app/views/restaurants/show.html.erb
  <div class="font-thin text-center my-8 text-xl flex-1">
  <p>
    Choose Branch
  </p>
</div>
<div class="w-1/4 flex flex-col flex-wrap  m-auto">
  <% @restaurant.branches.each do |b| %>
    <div class="rounded-lg overflow-hidden shadow-lg w-full h-24 text-left bg-white hover:bg-gray-200 mt-5 flex items-center m-auto">
      <img class="w-16 h-16 rounded-full mr-4 bg-sp-mn ml-2"/>
      <p class="text-lg text-gray-800">
      <%= link_to "#{b.city}, #{b.address}", restaurant_branch_path(@restaurant, b)%>
      </p>
    </div>
  <% end %>
</div>

<% if can? :create, Branch %>
<div class="flex justify-center mt-24">
<div class="flex flex-col justify-center h-24  my-3  mx-24  w-1/4 rounded-lg overflow-hidden shadow-lg m-4 bg-white card m-auto">
  <div class="font-bold text-lg mb-1 flex-1 text-center text-red-800">
    <p class="mt-4">
      Admin Control
    </p>
  </div>
    <%= link_to 'New Branch', new_restaurant_branch_path(@restaurant), class: "bg-gray-500 hover:bg-red-800 text-white font-bold py-2 px-4 rounded m-auto mt-2 mb-8" %>
  </div>
</div>
<% end %>