config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'application#index'
  devise_for :users#, :skip => :registrations
  
  resources :restaurants do
    resources :menu_items
    resources :branches do
      resources :orders do
        resources :order_lines
      end
    end
  end
  get 'restaurant/:city', to: 'restaurants#by_city', as: "by_city"
  get 'orders/', to: 'orders#orders', as: "orders"

  # devise_for :admins, class_name: 'Admin', skip: [:sessions, :registrations]
  # devise_for :vendors, class_name: 'Vendor', skip: :sessions
  # devise_for :customers, class_name: 'Customer', skip: :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="font-sans bg-gray-900 text-white py-8 px-4">
  <div class="mx-auto container overflow-hidden flex flex-col lg:flex-row justify-between">
    <p class="block mr-4 w-1/2" style="font-family: 'Gill Sans';font-weight: 300; font-size: 20px;letter-spacing: 3px;">
      Food Court
    </p>
    <div class="w-1/2 flex text-sm mt-6 lg:mt-0">
      <ul class="text-gray-700 list-none p-0 font-thin flex flex-col text-left">
        <li class="inline-block py-2 px-3 text-white uppercase no-underline font-medium tracking-wide">Restaurants</li>
      </ul>
      <ul class="text-gray-700 list-none p-0 font-thin flex flex-col text-left">
        <li class="inline-block py-2 px-3 text-white uppercase no-underline font-medium tracking-wide">This Site</li>
      </ul>
      <ul class="text-gray-700 list-none p-0 font-thin flex flex-col text-left">
        <li class="inline-block py-2 px-3 text-white uppercase no-underline font-medium tracking-wide">About</li>

      </ul>
      <div class="text-gray-700 flex flex-col">
        <div class="inline-block py-2 px-3 text-white uppercase font-medium tracking-wide">Follow Me</div>
        <div class="flex pl-4 justify-start">

        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<div class="bg-sp-mn">
    <nav class="font-sans  text-center flex justify-between py-4 mx-auto container overflow-hidden">
    <p class="block text-left  text-white w-1/2" style="font-family: 'Gill Sans';font-weight: 500; font-size: 20px;letter-spacing: 3px;">
      Food Court
    </p>
    <ul class="text-sm text-white list-none p-0 flex items-center">
        <li><%= link_to 'Home', root_path, class:"inline-block py-2 px-3 text-white hover:text-gray-300 no-underline"%></li>
        <li><%= link_to 'Restaurants', restaurants_path, class:"inline-block py-2 px-3 text-white hover:text-gray-300 no-underline"%></li>
        <%if !current_user%>
            <li class="pl-2 border-l"><%= link_to 'Log In', new_user_session_path, class:"inline-block py-2 px-3 text-white hover:text-gray-300 no-underline"%></li>
            <button class="bg-black hover:bg-text-gray-800 text-white ml-4 py-2 px-3">
            <%= link_to 'Sign Up', new_user_registration_path%>
            </button>
        <%else%>
            <li class="pl-2 border-l"><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class:"inline-block py-2 px-3 text-white hover:text-gray-300 no-underline"%></li>
            <li><%= link_to 'Your Orders', orders_path, class:"inline-block py-2 px-3 text-white hover:text-gray-300 no-underline"%></li>
            <%if current_user.admin?%>
                <li><%= link_to 'Dashboard', rails_admin_path, class:"bg-transparent border border-white hover:bg-text-gray-800 text-white ml-4 py-2 px-3 inline-block py-2 px-3 text-white hover:text-gray-300 no-underline"%></li>
            <%end%>
        <%end%>
    </ul>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodCourt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag    'application' %>
    <%= javascript_pack_tag 'application' %>
     <%# <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> %>
  </head>

  <body>
  
  
  <% flash.each do |type, message| %>
    <% if type == "alert" %>
      <div class="bg-red-500" id="alert">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
    <% if type == "notice" %>
      <div class="bg-green-500" id="notice">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
  <% end %>
  <%= render 'layouts/nav'%>



        <%= yield %>


    <%= render 'layouts/footer'%>
  </body>
</html>